# Generated by Django 6.1 on 2026-08-19 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_generated', models.BooleanField(default=True, editable=False, help_text='Generated rows are replaced when the year is generated again; added ones are not.')),
            ],
            options={
                'verbose_name': 'public holiday',
                'verbose_name_plural': 'public holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='from')),
                ('end_date', models.DateField(verbose_name='to')),
                ('deducts_leave', models.BooleanField(default=True, help_text='Off for a day the employer closes and pays for.', verbose_name='comes out of their leave')),
            ],
            options={
                'verbose_name': 'closure',
                'verbose_name_plural': 'closures',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('holiday', 'Holiday'), ('special', 'Special leave'), ('sick', 'Sick'), ('closure', 'Workplace closed')], default='holiday', max_length=10, verbose_name='reason')),
                ('start_date', models.DateField(verbose_name='from')),
                ('end_date', models.DateField(verbose_name='to')),
                ('status', models.CharField(choices=[('requested', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Declined'), ('withdrawn', 'Withdrawn')], default='requested', max_length=10, verbose_name='status')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=200, verbose_name='reply')),
                ('decided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employee', verbose_name='employee')),
                ('special_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='organisation.specialleavetype', verbose_name='which')),
                ('closure', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='absences.companyclosure')),
            ],
            options={
                'verbose_name': 'absence',
                'verbose_name_plural': 'absences',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', 'start_date'], name='absences_ab_employe_893789_idx'), models.Index(fields=['start_date', 'end_date'], name='absences_ab_start_d_9861ce_idx')],
            },
        ),
    ]
