# Generated by Django 6.1 on 2026-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='kind',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('special', 'Special leave'), ('sick', 'Sick'), ('closure', 'Workplace closed'), ('overtime', 'Time off in lieu')], default='holiday', max_length=10, verbose_name='reason'),
        ),
    ]
