# Generated by Django 6.1 on 2026-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_alter_absence_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='is_half_day',
            field=models.BooleanField(default=False, help_text='Half of that one day. Only for a single date.', verbose_name='half a day'),
        ),
    ]
