# Generated by Django 6.1 on 2026-08-20 18:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_absence_is_half_day'),
        ('employees', '0004_contract_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCarryOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='The year these days were carried into, not the year they were earned.', verbose_name='into the year')),
                ('statutory_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='statutory days carried')),
                ('employer_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='the employer’s extra, carried')),
                ('statutory_deadline', models.DateField(blank=True, null=True, verbose_name='statutory days lapse on')),
                ('employer_deadline', models.DateField(blank=True, null=True, verbose_name='the extra lapses on')),
                ('notice_given_on', models.DateField(blank=True, help_text='When they were told what was left and that it would lapse. Without this the statutory days are treated as not expiring at all.', null=True, verbose_name='they were told on')),
                ('extended_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('extension_reason', models.CharField(blank=True, help_text='Required to move a deadline. It is the only record of why this person’s is different.', max_length=200, verbose_name='why it was extended')),
                ('forfeited_statutory', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='statutory days lost')),
                ('forfeited_employer', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, verbose_name='extra days lost')),
                ('forfeited_on', models.DateField(blank=True, null=True, verbose_name='lost on')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carried_leave', to='employees.employee', verbose_name='employee')),
                ('extended_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'carried-over leave',
                'verbose_name_plural': 'carried-over leave',
                'ordering': ['-year', 'employee__first_name'],
                'indexes': [models.Index(fields=['employee', 'year'], name='absences_le_employe_b5b0ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year'), name='one_carry_over_per_year')],
            },
        ),
    ]
