# Generated by Django 6.1 on 2026-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_leavecarryover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('requested', 'Waiting for approval'), ('approved', 'Approved'), ('cancelling', 'Cancellation requested'), ('rejected', 'Declined'), ('withdrawn', 'Withdrawn')], default='requested', max_length=10, verbose_name='status'),
        ),
    ]
