# Generated by Django 6.1 on 2026-08-19 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_format', models.CharField(choices=[('decimal', 'decimal — 7,5 h'), ('clock', 'clock — 7:30 h')], default='decimal', help_text='How durations are written on every page that shows one.', max_length=10, verbose_name='hours')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferences',
                'verbose_name_plural': 'preferences',
            },
        ),
        migrations.CreateModel(
            name='SSOConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='With this off, the local password form is the only way in.', verbose_name='offer single sign-on')),
                ('op_base', models.URLField(blank=True, help_text='The issuer, e.g. https://sso.example.org — or paste the full …/.well-known/openid-configuration address if that is what your provider gives you.', max_length=500, verbose_name='SSO server')),
                ('authorization_endpoint', models.URLField(blank=True, max_length=500, verbose_name='authorisation endpoint')),
                ('token_endpoint', models.URLField(blank=True, max_length=500, verbose_name='token endpoint')),
                ('user_endpoint', models.URLField(blank=True, max_length=500, verbose_name='user info endpoint')),
                ('jwks_endpoint', models.URLField(blank=True, max_length=500, verbose_name='JWKS endpoint')),
                ('endpoints_read_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('client_id', models.CharField(blank=True, max_length=200, verbose_name='client ID')),
                ('client_secret_encrypted', models.TextField(blank=True, editable=False)),
                ('sign_algo', models.CharField(choices=[('RS256', 'RS256 — signed with the provider’s key (needs the JWKS endpoint)'), ('HS256', 'HS256 — signed with the client secret (no key fetch)')], default='RS256', max_length=10, verbose_name='signature algorithm')),
                ('scopes', models.CharField(default='openid profile email', help_text='Separated by spaces.', max_length=200, verbose_name='scopes')),
                ('allowed_groups', models.CharField(blank=True, help_text='Separated by commas. Empty means anybody the SSO server authenticates.', max_length=300, verbose_name='allowed groups')),
                ('groups_claim', models.CharField(default='groups', help_text='The claim the group names arrive in. Some providers send none at all.', max_length=100, verbose_name='group claim')),
                ('staff_group', models.CharField(blank=True, help_text='Members of this group may manage people. Re-applied at every sign-in.', max_length=200, verbose_name='administrator group')),
                ('verify_ssl', models.BooleanField(default=True, help_text='Leave on. Verification is the whole point of putting the SSO server behind a real certificate.', verbose_name='verify the certificate')),
                ('request_timeout', models.PositiveSmallIntegerField(default=10, help_text='Seconds to wait for the provider before giving up.', verbose_name='request timeout')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSO configuration',
                'verbose_name_plural': 'SSO configuration',
            },
        ),
        migrations.CreateModel(
            name='SSOIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, verbose_name='subject')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('matched_by_email', models.BooleanField(default=False, help_text='Attached to an account that already existed, rather than creating one.', verbose_name='matched by e-mail address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_identity', to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'verbose_name': 'provider identity',
                'verbose_name_plural': 'provider identities',
            },
        ),
    ]
