# Generated by Django 6.1 on 2026-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssoidentity',
            name='provider_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='directory name'),
        ),
    ]
