# Generated by Django 6.1 on 2026-09-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ssoidentity_provider_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
