# Generated by Django 6.1 on 2026-08-19 18:23

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('full_time_days_per_week', models.PositiveSmallIntegerField(default=5, help_text='The divisor for everybody’s leave. Five for a Monday-to-Friday business.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='full-time working days per week')),
                ('full_time_leave_days', models.DecimalField(decimal_places=1, default=Decimal('30.0'), help_text='What somebody working a full week is entitled to. The statutory minimum is 20 on a five-day week.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='full-time leave days per year')),
                ('leave_rounding', models.CharField(choices=[('up', 'always up — 16.8 days becomes 17'), ('half', 'to the nearest half day — 16.8 becomes 17, 16.6 becomes 16.5'), ('exact', 'leave the fraction — 16.8 stays 16.8')], default='up', help_text='What happens to the fraction when the entitlement does not come out whole.', max_length=10, verbose_name='rounding')),
                ('land', models.CharField(choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bavaria'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hesse'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Lower Saxony'), ('NW', 'North Rhine-Westphalia'), ('RP', 'Rhineland-Palatinate'), ('SL', 'Saarland'), ('SN', 'Saxony'), ('ST', 'Saxony-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thuringia')], default='BW', help_text='Which public holidays apply. Nine of the thirteen differ by Land.', max_length=2, verbose_name='federal state')),
                ('day_start', models.TimeField(default=datetime.time(8, 0), help_text='Used only when filling a week from the contracts, as the first draft.', verbose_name='the day usually starts at')),
            ],
            options={
                'verbose_name': 'working time settings',
                'verbose_name_plural': 'working time settings',
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('mode', models.CharField(choices=[('fixed', 'the same for everybody who has it'), ('pro_rata', 'scaled by working days, like the annual leave'), ('threshold', 'from a table of working days per week')], default='pro_rata', max_length=12, verbose_name='how it is worked out')),
                ('days', models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='For “the same for everybody”, the number itself. For “scaled”, what a full-time employee would get.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='days')),
                ('is_active', models.BooleanField(default=True, help_text='Switching this off keeps the leave already taken and stops it being granted to anybody new.', verbose_name='offered')),
            ],
            options={
                'verbose_name': 'special leave type',
                'verbose_name_plural': 'special leave types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BreakRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_minutes', models.PositiveSmallIntegerField(help_text='In minutes. 360 is six hours.', verbose_name='working time over')),
                ('break_minutes', models.PositiveSmallIntegerField(help_text='In minutes.', verbose_name='break')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_rules', to='organisation.orgsettings')),
            ],
            options={
                'verbose_name': 'break rule',
                'verbose_name_plural': 'break rules',
                'ordering': ['over_minutes'],
                'constraints': [models.UniqueConstraint(fields=('settings', 'over_minutes'), name='one_rule_per_threshold')],
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaveThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days_per_week', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='working days per week, at least')),
                ('days', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='days')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='organisation.specialleavetype')),
            ],
            options={
                'verbose_name': 'threshold',
                'verbose_name_plural': 'thresholds',
                'ordering': ['min_days_per_week'],
                'constraints': [models.UniqueConstraint(fields=('leave_type', 'min_days_per_week'), name='one_threshold_per_day_count')],
            },
        ),
    ]
