# Generated by Django 6.1 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='time_zone',
            field=models.CharField(default='Europe/Berlin', help_text='The clock the workplace keeps. Somebody who works elsewhere can be given their own on their contract.', max_length=64, verbose_name='time zone'),
        ),
    ]
