# Generated by Django 6.1 on 2026-08-20 18:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_orgsettings_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='employer_deadline_day',
            field=models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='the employer’s deadline — day'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='employer_deadline_month',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='the employer’s deadline — month'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='employer_expires',
            field=models.BooleanField(default=True, verbose_name='the employer’s extra expires'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='statutory_deadline_day',
            field=models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='statutory carry-over deadline — day'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='statutory_deadline_month',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='statutory carry-over deadline — month'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='statutory_expires',
            field=models.BooleanField(default=True, help_text='Switch off to carry it indefinitely, which is what an employer who does not send the reminder should assume.', verbose_name='statutory leave expires'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='statutory_leave_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('20.0'), help_text='The protected part, for somebody working a full week. 20 days on a five-day week is the statutory minimum. Anything above it is the employer’s own and may expire on the employer’s own terms.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='of which statutory, per year'),
        ),
    ]
