# Generated by Django 6.1 on 2026-09-03 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_orgsettings_employer_deadline_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='keep_absences_years',
            field=models.PositiveSmallIntegerField(default=10, help_text='Leave, sickness and what was carried over.', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(30)], verbose_name='keep time off and sickness for (years)'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='keep_audit_years',
            field=models.PositiveSmallIntegerField(default=10, help_text='It cannot be kept for less than the records it explains — a trail that expires first leaves them unaccounted for. A shorter figure is raised to the longest of the three above.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='keep the audit trail for (years)'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='keep_roster_years',
            field=models.PositiveSmallIntegerField(default=2, help_text='What people were asked to work. No statute requires keeping a plan, and it stops being useful once the timesheet beside it has gone.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='keep the roster for (years)'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='keep_security_log_years',
            field=models.PositiveSmallIntegerField(default=1, help_text='Who signed in, who was refused. Art. 32 DSGVO wants the log to exist and no statute says how long — the one period here where longer is harder to defend rather than easier.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='keep sign-ins for (years)'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='keep_working_time_years',
            field=models.PositiveSmallIntegerField(default=10, help_text='Days, bookings and closed months. Two years is the statutory minimum (§16 ArbZG, §17 MiLoG); the wage account they support is six, and social insurance longer still.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='keep working time for (years)'),
        ),
    ]
