# Generated by Django 6.1 on 2026-09-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_orgsettings_keep_absences_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialleavetype',
            name='note',
            field=models.CharField(blank=True, help_text='Where the entitlement comes from, and anything about it the app does not work out for itself. Shown to a manager beside the grant on somebody’s contract — which is the moment they need to know it.', max_length=300, verbose_name='what this is'),
        ),
    ]
