# Generated by Django 6.1 on 2026-08-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start', models.TimeField(verbose_name='from')),
                ('end', models.TimeField(verbose_name='to')),
                ('note', models.CharField(blank=True, help_text='Shown on the card — “group 2”, “outing”, anything the shift needs saying about.', max_length=100, verbose_name='note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
                'ordering': ['date', 'start', 'employee__first_name'],
                'indexes': [models.Index(fields=['date'], name='roster_shif_date_b8338a_idx'), models.Index(fields=['employee', 'date'], name='roster_shif_employe_8186a6_idx')],
            },
        ),
    ]
