# Generated by Django 6.1 on 2026-09-03 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_opening_balance_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='when')),
                ('action', models.CharField(choices=[('created', 'created'), ('changed', 'changed'), ('deleted', 'deleted'), ('locked', 'locked'), ('unlocked', 'unlocked'), ('viewed', 'looked at'), ('exported', 'exported'), ('signed-in', 'signed in'), ('sign-in-refused', 'sign-in refused'), ('signed-out', 'signed out')], max_length=20, verbose_name='what happened')),
                ('actor_label', models.CharField(default='system', max_length=150, verbose_name='who')),
                ('employee_label', models.CharField(blank=True, max_length=150, verbose_name='about')),
                ('subject', models.CharField(blank=True, max_length=64, verbose_name='record')),
                ('subject_id', models.CharField(blank=True, max_length=40)),
                ('subject_date', models.DateField(blank=True, db_index=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='employees.employee')),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit entries',
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['employee', '-at'], name='audit_audit_employe_6354eb_idx'), models.Index(fields=['actor', '-at'], name='audit_audit_actor_i_e548ba_idx'), models.Index(fields=['subject', 'subject_id'], name='audit_audit_subject_0bcac3_idx'), models.Index(fields=['action', '-at'], name='audit_audit_action_664d64_idx')],
            },
        ),
    ]
