# Generated by Django 6.1 on 2026-08-19 18:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='surname')),
                ('email', models.EmailField(blank=True, help_text='Only used to recognise them when they first sign in through the provider.', max_length=254, verbose_name='e-mail')),
                ('is_manager', models.BooleanField(default=False, help_text='May plan the roster, see everybody’s timesheets and decide requests.', verbose_name='manages the team')),
                ('is_active', models.BooleanField(default=True, help_text='Switching this off keeps every hour they have worked and takes them off the roster.', verbose_name='employed')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='started on')),
                ('ended_on', models.DateField(blank=True, help_text='After this date they are not rostered and their leave stops accruing.', null=True, verbose_name='left on')),
                ('hours_mon', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Monday')),
                ('hours_tue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Tuesday')),
                ('hours_wed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Wednesday')),
                ('hours_thu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Thursday')),
                ('hours_fri', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Friday')),
                ('hours_sat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Saturday')),
                ('hours_sun', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('24'))], verbose_name='Sunday')),
                ('leave_days_override', models.DecimalField(blank=True, decimal_places=1, help_text='Leave empty to work it out from the working days. Fill it in only for a contract that says something else.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='leave days')),
                ('user', models.OneToOneField(blank=True, help_text='Filled in by itself when they first sign in, if the e-mail addresses match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['-is_active', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaveGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_override', models.DecimalField(blank=True, decimal_places=1, help_text='Leave empty to use the type’s own rule.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='days')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_leave', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='organisation.specialleavetype', verbose_name='leave type')),
            ],
            options={
                'verbose_name': 'special leave',
                'verbose_name_plural': 'special leave',
                'ordering': ['leave_type__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type'), name='one_grant_per_type')],
            },
        ),
    ]
