# Generated by Django 6.1 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='time_zone',
            field=models.CharField(blank=True, help_text='Leave empty unless they work in a different one from the workplace.', max_length=64, verbose_name='time zone'),
        ),
    ]
