# Generated by Django 6.1 on 2026-08-20 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_contract_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='opening_balance_minutes',
            field=models.IntegerField(default=0, help_text='Hours already owed to them, or by them, when they started here. Leave at nought unless something was agreed.', verbose_name='hours brought with them'),
        ),
        migrations.AddField(
            model_name='employee',
            name='opening_balance_on',
            field=models.DateField(blank=True, help_text='The date those figures were true. Usually the day they started.', null=True, verbose_name='as at'),
        ),
        migrations.AddField(
            model_name='employee',
            name='opening_leave_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Days of leave carried in from wherever they were before.', max_digits=5, verbose_name='leave days brought with them'),
        ),
    ]
