# Generated by Django 6.1 on 2026-09-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_opening_balance_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialleavegrant',
            name='override_reason',
            field=models.CharField(blank=True, help_text='Only needed when the days above are set by hand.', max_length=200, verbose_name='why'),
        ),
    ]
