# Generated by Django 6.1 on 2026-08-19 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, help_text='In minutes.', verbose_name='break')),
                ('break_is_override', models.BooleanField(default=False, editable=False, verbose_name='break entered by hand')),
                ('source', models.CharField(choices=[('roster', 'confirmed as rostered'), ('manual', 'entered by hand')], default='manual', editable=False, max_length=10)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('confirmed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='employees.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('start', models.TimeField(verbose_name='from')),
                ('end', models.TimeField(verbose_name='to')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='timesheets.dayrecord')),
            ],
            options={
                'verbose_name': 'work segment',
                'verbose_name_plural': 'work segments',
                'ordering': ['position', 'start'],
            },
        ),
        migrations.AddIndex(
            model_name='dayrecord',
            index=models.Index(fields=['employee', 'date'], name='timesheets__employe_d52a37_idx'),
        ),
        migrations.AddConstraint(
            model_name='dayrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='one_record_per_day'),
        ),
    ]
