# Generated by Django 6.1 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksegment',
            name='end',
            field=models.TimeField(blank=True, help_text='Leave empty while the shift is still running.', null=True, verbose_name='to'),
        ),
    ]
