# Generated by Django 6.1 on 2026-09-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_worksegment_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayrecord',
            name='correction_minutes',
            field=models.SmallIntegerField(default=0, help_text='Minutes added to — or taken off — this day by hand.', verbose_name='correction'),
        ),
        migrations.AddField(
            model_name='dayrecord',
            name='correction_reason',
            field=models.CharField(blank=True, help_text='Required whenever there is a correction.', max_length=200, verbose_name='why'),
        ),
    ]
