# Generated by Django 6.1 on 2026-09-01 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_opening_balance_minutes_and_more'),
        ('timesheets', '0003_dayrecord_correction_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='employees.employee', verbose_name='employee')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'locked day',
                'verbose_name_plural': 'locked days',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='timesheets__employe_6224f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='one_lock_per_day')],
            },
        ),
    ]
