# Generated by Django 6.1 on 2026-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_daylock'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayrecord',
            name='hours_entered_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
