# Generated by Django 6.1 on 2026-09-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_dayrecord_hours_entered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='confirmed at'),
        ),
        migrations.AlterField(
            model_name='dayrecord',
            name='hours_entered_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='hours first recorded at'),
        ),
        migrations.AlterField(
            model_name='dayrecord',
            name='source',
            field=models.CharField(choices=[('roster', 'confirmed as rostered'), ('manual', 'entered by hand')], default='manual', editable=False, max_length=10, verbose_name='how it was entered'),
        ),
    ]
